security:
    # Hiérarchie : ROLE_ADMIN hérite de ROLE_USER (un admin peut tout faire qu'un user peut faire)
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\User: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: app_home

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Sécurité des routes
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/posts/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/posts$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/posts/create, roles: ROLE_USER }
        - { path: ^/posts/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/posts/\d+/delete, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # Hashage des mots de passe pour la sécurité.
            # Dans les tests, il est sûr de réduire leur coût pour améliorer les performances.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse possible pour bcrypt
                time_cost: 3 # Valeur la plus basse possible pour argon
                memory_cost: 10 # Valeur la plus basse possible pour argon
